version: "3"
services:
  ravendb:
    image: ravendb/ravendb
    ports:
      - "8080:8080"
    environment:
      RAVEN_License_Eula_Accepted: "true"
      RAVEN_Setup_Mode: None
  seq:
    image: datalust/seq
    ports:
      - "5341:5341"
      - "15341:80"
    environment:
      ACCEPT_EULA: "Y"
