version: "3"
services:
  ravendb:
    image: ravendb/ravendb
    ports:
      - "8282:8080"
    environment:
      RAVEN_License_Eula_Accepted: "true"
      RAVEN_Setup_Mode: None
    volumes:
      - ravendb-data-volume:/opt/RavenDB/Server/RavenData
  seq:
    image: datalust/seq
    ports:
      - "5342:5341"
      - "15342:80"
    environment:
      ACCEPT_EULA: "Y"
    volumes:
      - seq-data-volume:/data

volumes:
  ravendb-data-volume:
  seq-data-volume:
